name: 'Revise git comments'
inputs:
  githubToken:
    required: true
  repos:
    required: true  
  issueNo:
    required: true
  prefix:
    required: false
    default: 'feature'
  from:
    required: false
    default: 'develop'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.githubToken }}
    - ${{ inputs.repos }}
    - ${{ inputs.issueNo }}
    - ${{ inputs.prefix }}
    - ${{ inputs.from }}
