name: 'Give issue no to comments'
description: 'Prepend the issue no to all comments of unique commit in the branch.'

inputs:
  issueNo:
    required: true
  branch:
    required: false
    default: ${{ github.head_ref }}
  token:
    required: false
    default: ${{ github.token }}
  repos:  
    required: false
    default: ${{ github.repository }}
  baseBranch:
    required: false
    default: 'develop'
  userName:
    required: false
    default: 'begyyal-ghost'
  userMail:
    required: false
    default: 'begyyal@gmail.com'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.issueNo }}
    - ${{ inputs.branch }}
    - ${{ inputs.token }}
    - ${{ inputs.repos }}
    - ${{ inputs.baseBranch }}
    - ${{ inputs.userName }}
    - ${{ inputs.userMail }}
    
branding:
  icon: 'message-square'
  color: 'red'
