name: 'Give a prefix to comments'
description: 'Prepend a prefix to all comments of unique commit in the branch.'

inputs:
  prefix:
    required: true
  branch:
    required: false
    default: ${{ github.head_ref }}
  token:
    required: false
    default: ${{ github.token }}
  repos:  
    required: false
    default: ${{ github.repository }}
  baseBranch:
    required: false
    default: ${{ github.base_ref }}
  userName:
    required: false
    default: 'begyyal-ghost'
  userMail:
    required: false
    default: 'begyyal@gmail.com'
  omitSpaceFlag:
    required: false
    default: ''
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.prefix }}
    - ${{ inputs.branch }}
    - ${{ inputs.token }}
    - ${{ inputs.repos }}
    - ${{ inputs.baseBranch }}
    - ${{ inputs.userName }}
    - ${{ inputs.userMail }}
    - ${{ inputs.omitSpaceFlag }}
    
branding:
  icon: 'message-square'
  color: 'red'
