name: 'Revise git comments'
inputs:
  issueNo:
    required: true
  token:
    required: false
    default: ${{ github.token }}
  repos:  
    required: false
    default: ${{ github.repository }}
  prefix:
    required: false
    default: 'feature'
  from:
    required: false
    default: 'develop'
  userName:
    required: false
    default: 'begyyal-ghost'
  userMail:
    required: false
    default: 'begyyal@gmail.com'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.issueNo }}
    - ${{ inputs.token }}
    - ${{ inputs.repos }}
    - ${{ inputs.prefix }}
    - ${{ inputs.from }}
    - ${{ inputs.userName }}
    - ${{ inputs.userMail }}
